// Date: 28.05.2013 20:45:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package sanandreasp.mods.EnderStuffPlus.client.model;

import net.minecraft.client.model.ModelEnderman;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnderNemesis extends ModelEnderman
{
	//fields
//	ModelRenderer Head;
//	ModelRenderer Headwear;
//	ModelRenderer Body;
//	ModelRenderer RightArm;
//	ModelRenderer LeftArm;
//	ModelRenderer RightLeg;
//	ModelRenderer LeftLeg;
	ModelRenderer RightWing;
	ModelRenderer LeftWing;
	ModelRenderer Heart;
	
	public ModelEnderNemesis() {
		super();
		textureWidth = 64;
		textureHeight = 32;

//		Head = new ModelRenderer(this, 0, 0);
//		Head.addBox(-4F, -8F, -4F, 8, 8, 8);
//		Head.setRotationPoint(0F, -14F, 0F);
//		Head.setTextureSize(64, 32);
//		Head.mirror = true;
//		setRotation(Head, 0F, 0F, 0F);
//		Headwear = new ModelRenderer(this, 0, 16);
//		Headwear.addBox(-4F, -8F, -4F, 8, 8, 8);
//		Headwear.setRotationPoint(0F, -14F, 0F);
//		Headwear.setTextureSize(64, 32);
//		Headwear.mirror = true;
//		setRotation(Headwear, 0F, 0F, 0F);
//		Body = new ModelRenderer(this, 32, 16);
//		Body.addBox(-4F, 0F, -2F, 8, 12, 4);
//		Body.setRotationPoint(0F, -14F, 0F);
//		Body.setTextureSize(64, 32);
//		Body.mirror = true;
//		setRotation(Body, 0F, 0F, 0F);
//		RightArm = new ModelRenderer(this, 56, 0);
//		RightArm.addBox(-1F, -2F, -1F, 2, 30, 2);
//		RightArm.setRotationPoint(-5F, -12F, 0F);
//		RightArm.setTextureSize(64, 32);
//		RightArm.mirror = true;
//		setRotation(RightArm, 0F, 0F, 0F);
//		LeftArm.mirror = true;
//		LeftArm = new ModelRenderer(this, 56, 0);
//		LeftArm.addBox(-1F, -2F, -1F, 2, 30, 2);
//		LeftArm.setRotationPoint(5F, -12F, 0F);
//		LeftArm.setTextureSize(64, 32);
//		LeftArm.mirror = true;
//		setRotation(LeftArm, 0F, 0F, 0F);
//		LeftArm.mirror = false;
//		RightLeg = new ModelRenderer(this, 56, 0);
//		RightLeg.addBox(-1F, 0F, -1F, 2, 30, 2);
//		RightLeg.setRotationPoint(-2F, -2F, 0F);
//		RightLeg.setTextureSize(64, 32);
//		RightLeg.mirror = true;
//		setRotation(RightLeg, 0F, 0F, 0F);
//		LeftLeg.mirror = true;
//		LeftLeg = new ModelRenderer(this, 56, 0);
//		LeftLeg.addBox(-1F, 0F, -1F, 2, 30, 2);
//		LeftLeg.setRotationPoint(2F, -2F, 0F);
//		LeftLeg.setTextureSize(64, 32);
//		LeftLeg.mirror = true;
//		setRotation(LeftLeg, 0F, 0F, 0F);
//		LeftLeg.mirror = false;
		RightWing = new ModelRenderer(this, 40, -2);
		RightWing.addBox(0F, 0F, 0F, 0, 12, 2);
		RightWing.setRotationPoint(-2F, -14F, 1F);
		RightWing.setTextureSize(64, 32);
		RightWing.mirror = true;
		setRotation(RightWing, -0.0523599F, 1.099557F, 0.2443461F);
		LeftWing = new ModelRenderer(this, 32, -4);
		LeftWing.addBox(0F, 0F, 0F, 0, 16, 4);
		LeftWing.setRotationPoint(4F, -14F, 0F);
		LeftWing.setTextureSize(64, 32);
		LeftWing.mirror = true;
		setRotation(LeftWing, 0.1396263F, -0.7504916F, -0.0872665F);
		Heart = new ModelRenderer(this, 26, 0);
		Heart.addBox(-1F, -1F, 0F, 2, 2, 1);
		Heart.setRotationPoint(2F, -11F, -2.5F);
		Heart.setTextureSize(64, 32);
		Heart.mirror = true;
		setRotation(Heart, 0F, 0F, 0F);
	}
	
	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
//		super.setRotationAngles(f, f1, f2, f3, f4, f5);
//		Head.render(f5);
//		Headwear.render(f5);
//		Body.render(f5);
//		RightArm.render(f5);
//		LeftArm.render(f5);
//		RightLeg.render(f5);
//		LeftLeg.render(f5);
		setRotation(RightWing, 0.1523599F, 0.699557F, 0.2443461F);
		RightWing.render(f5);
		LeftWing.render(f5);
		Heart.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
//	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
//	{
//		super.setRotationAngles(f, f1, f2, f3, f4, f5);
//	}
}
